language: java
jdk: openjdk7
notifications:
  email: false
  slack:
    secure: TODO
env:
  global:
  - TERM=dumb

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew curseforge -S
    on:
      all_branches: true
      repo: <%= repo %>
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: TODO
    on:
      all_branches: true
      repo: <%= repo %>
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./gradlew uploadArchives -S
    on:
      all_branches: true
      repo: <%= repo %>
      condition: "$TRAVIS_BRANCH =~ ^(master|release).*$"
